/**
 * OGANI REST API DOCUMENT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: phamhai.bvh@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Tag } from './tag';
import { Image } from './image';


export interface Blog { 
    id?: number;
    title?: string;
    description?: string;
    content?: string;
    createAt?: string;
    image?: Image;
    user?: User;
    tags?: Set<Tag>;
}

