/**
 * OGANI REST API DOCUMENT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: phamhai.bvh@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateBlogRequest { 
    title: string;
    description: string;
    content: string;
    imageId: number;
    username?: string;
    tags?: Set<number>;
}

