/**
 * OGANI REST API DOCUMENT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: phamhai.bvh@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProductRequest { 
    /**
     * Tên sản phẩm
     */
    name: string;
    /**
     * Mô tả sản phẩm
     */
    description: string;
    /**
     * Giá sản phẩm
     */
    price: number;
    /**
     * Số lượng sản phẩm
     */
    quantity: number;
    /**
     * ID của danh mục
     */
    categoryId: number;
    /**
     * Mảng Id của hình ảnh
     */
    imageIds: Set<number>;
}

