/**
 * OGANI REST API DOCUMENT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: phamhai.bvh@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateOrderDetailRequest } from './createOrderDetailRequest';


export interface CreateOrderRequest { 
    firstname: string;
    lastname: string;
    country: string;
    address: string;
    town: string;
    state: string;
    postCode: number;
    email: string;
    phone: string;
    note?: string;
    totalPrice?: number;
    username?: string;
    orderDetails?: Array<CreateOrderDetailRequest>;
}

