/**
 * OGANI REST API DOCUMENT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: phamhai.bvh@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Role { 
    id?: number;
    name?: Role.NameEnum;
}
export namespace Role {
    export type NameEnum = 'ROLE_USER' | 'ROLE_MODERATOR' | 'ROLE_ADMIN';
    export const NameEnum = {
        User: 'ROLE_USER' as NameEnum,
        Moderator: 'ROLE_MODERATOR' as NameEnum,
        Admin: 'ROLE_ADMIN' as NameEnum
    };
}


