/**
 * OGANI REST API DOCUMENT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: phamhai.bvh@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface User { 
    id?: number;
    username?: string;
    email?: string;
    firstname?: string;
    lastname?: string;
    password?: string;
    country?: string;
    state?: string;
    address?: string;
    phone?: string;
    verificationCode?: string;
    enabled?: boolean;
    roles?: Set<Role>;
}

